<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>GIS Final Project: Berry Cultivation in Jalisco</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d38567ed42e5b1b33fd4dce5d7fc7ec5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: black;
      }

      .quarto-title-block .quarto-title-banner {
        color: black;
background: #E69F0095;
      }
</style>


<meta name="citation_title" content="GIS Final Project: Berry Cultivation in Jalisco">
<meta name="citation_author" content="Juan Pablo Fernandez">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Myanmar’s military built a new capital as a haven for power. Other countries have tried that, too.;,citation_abstract=Saturday saw the first street protests of Myanmar’s military takeover despite the threat of repression.;,citation_author=Miriam Berger;,citation_publication_date=2021-02;,citation_cover_date=2021-02;,citation_year=2021;,citation_fulltext_html_url=https://www.washingtonpost.com/world/2021/02/06/myanmars-military-built-new-capital-haven-power-other-countries-have-tried-that-too/;,citation_issn=0190-8286;,citation_language=en-US;,citation_journal_title=Washington Post;">
<meta name="citation_reference" content="citation_title=Capital Cities, Conflict, and Misgovernance;,citation_abstract=We investigate the links between capital cities, conflict, and the quality of governance, starting from the assumption that incumbent elites are constrained by the threat of insurrection, and that the latter is rendered less effective by distance from the seat of political power. We show evidence that (i) conflict is more likely to emerge (and dislodge incumbents) closer to the capital, and (ii) isolated capitals are associated with misgovernance. The results hold only for relatively nondemocratic countries and for intrastate conflicts over government (as opposed to territory)—exactly the cases where our central assumption should apply.;,citation_author=Filipe R. Campante;,citation_author=Quoc-Anh Do;,citation_author=Bernardo Guimaraes;,citation_publication_date=2019-07;,citation_cover_date=2019-07;,citation_year=2019;,citation_fulltext_html_url=https://www.aeaweb.org/articles?id=10.1257/app.20170111;,citation_issue=3;,citation_doi=10.1257/app.20170111;,citation_issn=1945-7782;,citation_volume=11;,citation_language=en-US;,citation_journal_title=American Economic Journal: Applied Economics;">
<meta name="citation_reference" content="citation_title=Population centroids of the world administrative units from nighttime lights 1992-2013;,citation_abstract=Knowledge about the past, current and future distribution of the human population is fundamental for tackling many global challenges. Censuses are used to collect information about population within a specified spatial unit. The spatial units are usually arbitrarily defined and their numbers, size and shape tend to change over time. These issues make comparisons between areas and countries difficult. We have in related work proposed that the shape of the lit area derived from nighttime lights, weighted by its intensity can be used to analyse characteristics of the population distribution, such as the mean centre of population. We have processed global nighttime lights data for the period 1992–2013 and derived centroids for administrative levels 0–2 of the Database of Global Administrative Areas, corresponding to nations and two levels of sub-divisions, that can be used to analyse patterns of global or local population changes. The consistency of the produced dataset was investigated and distance between true population centres and derived centres are compared using Swedish census data as a benchmark.;,citation_author=Ola Hall;,citation_author=Maria Francisca Archila Bustos;,citation_author=Niklas Boke Olén;,citation_author=Thomas Niedomysl;,citation_publication_date=2019-10;,citation_cover_date=2019-10;,citation_year=2019;,citation_fulltext_html_url=https://www.nature.com/articles/s41597-019-0250-z;,citation_issue=1;,citation_doi=10.1038/s41597-019-0250-z;,citation_issn=2052-4463;,citation_volume=6;,citation_language=en-US;,citation_journal_title=Scientific Data;,citation_publisher=Nature Publishing Group;">
<meta name="citation_reference" content="citation_title=Equatorial Guinea: Obiang’s future capital, Oyala;,citation_abstract=The people of Equatorial Guinea ought to be among the world’s wealthiest - but somehow the country’s income from oil and timber doesn’t reach them.;,citation_author=Stephen Sackur;,citation_publication_date=2012-12;,citation_cover_date=2012-12;,citation_year=2012;,citation_fulltext_html_url=https://www.bbc.com/news/magazine-20731448;,citation_language=en-GB;,citation_journal_title=BBC News;">
</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">GIS Final Project: Berry Cultivation in Jalisco</h1>
            <p class="subtitle lead">DSAN 6750 / PPOL 6805: GIS for Spatial Data Science</p>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Author</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Juan Pablo Fernandez <a href="mailto:jf1677@georgetown.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Georgetown University
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></p></div><div class="quarto-title-meta-contents"><p><a href="index-meca.zip" data-meca-link="true"><i class="bi bi-archive"></i>MECA Bundle</a></p></div></div></div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-berries-production-in-jalisco-and-their-importance-for-rural-development" id="toc-introduction-berries-production-in-jalisco-and-their-importance-for-rural-development" class="nav-link active" data-scroll-target="#introduction-berries-production-in-jalisco-and-their-importance-for-rural-development">Introduction: Berries’ production in Jalisco and their importance for rural development</a></li>
  <li><a href="#project-design" id="toc-project-design" class="nav-link" data-scroll-target="#project-design">Project design</a></li>
  <li><a href="#hypothesis-framing-the-research-question" id="toc-hypothesis-framing-the-research-question" class="nav-link" data-scroll-target="#hypothesis-framing-the-research-question">Hypothesis framing the research question</a></li>
  <li><a href="#initial-coding-and-data-preparation" id="toc-initial-coding-and-data-preparation" class="nav-link" data-scroll-target="#initial-coding-and-data-preparation">Initial coding and data preparation</a></li>
  <li><a href="#variables-used-for-spatial-analysis" id="toc-variables-used-for-spatial-analysis" class="nav-link" data-scroll-target="#variables-used-for-spatial-analysis">Variables used for spatial analysis</a></li>
  <li><a href="#simple-visualization-of-spatial-data" id="toc-simple-visualization-of-spatial-data" class="nav-link" data-scroll-target="#simple-visualization-of-spatial-data">Simple visualization of spatial data</a></li>
  <li><a href="#non-spatial-correlation" id="toc-non-spatial-correlation" class="nav-link" data-scroll-target="#non-spatial-correlation">Non-Spatial Correlation</a></li>
  <li><a href="#spatial-correlation-morans-i" id="toc-spatial-correlation-morans-i" class="nav-link" data-scroll-target="#spatial-correlation-morans-i">Spatial Correlation: Moran’s I</a></li>
  <li><a href="#spatial-lag-regresion" id="toc-spatial-lag-regresion" class="nav-link" data-scroll-target="#spatial-lag-regresion">Spatial Lag Regresion</a></li>
  <li><a href="#conclusion-of-the-spatial-analysis" id="toc-conclusion-of-the-spatial-analysis" class="nav-link" data-scroll-target="#conclusion-of-the-spatial-analysis">Conclusion of the spatial analysis</a></li>
  <li><a href="#sources-of-information-and-data" id="toc-sources-of-information-and-data" class="nav-link" data-scroll-target="#sources-of-information-and-data">Sources of information and data</a></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="index-preview.html"><i class="bi bi-journal-code"></i>Article Notebook</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="introduction-berries-production-in-jalisco-and-their-importance-for-rural-development" class="level2">
<h2 class="anchored" data-anchor-id="introduction-berries-production-in-jalisco-and-their-importance-for-rural-development">Introduction: Berries’ production in Jalisco and their importance for rural development</h2>
<p>Berry cultivation — including strawberries, raspberries, blueberries, and blackberries — has become one of the most dynamic agricultural activities in Jalisco. These crops are considered high‑value and are strongly export‑oriented, contributing significantly to the rural economy and positioning Mexico as a global leader in berry exports.</p>
<p>According to the Mexican government, berries are the second agricultural product with the highest export value nationwide, underscoring their strategic importance for rural development and the competitiveness of Jalisco’s agricultural sector (SENASICA 2025). This expansion presents an opportunity to design rural development strategies that support the sector through targeted investments in technology, infrastructure, and labor training.</p>
<p>However, for such policies to be effective, it is essential that the government understands the spatial distribution of berry cultivation and the factors explaining these patterns. Evidence‑based policymaking can ensure that subsidies and support programs are directed to municipalities where agroclimatic conditions, labor availability, and logistical advantages combine to maximize the impact of public investment.</p>
</section>
<section id="project-design" class="level2">
<h2 class="anchored" data-anchor-id="project-design">Project design</h2>
<p>This project investigates the spatial determinants of berry cultivation in Jalisco, Mexico, focusing on strawberries, raspberries, blueberries, and blackberries. Using municipality-level data, I will model the relationship between agroclimatic suitability (altitude, precipitation, temperature, and water availability) and the surface area cultivated with berries. I will then incorporate proximity to federal highways to account for logistical advantages in export-oriented production. Moreover, as a labor-intensive crop, the model will also consider the number of workers employed in agriculture.</p>
<p>To test for spatial clustering effects beyond these variables, I will estimate a spatial lag regression model, assessing whether the presence of neighboring plantations significantly improves predictive power. I will use Moran’s I to measure spatial autocorrelation in the residuals before and after introducing the spatial lag term, allowing me to evaluate whether clustering is driven by unobserved spatial dynamics such as access to specialized services or cold storage.</p>
<p>The findings aim to inform rural development strategies by identifying spatial barriers and opportunities for expanding high-value agriculture.</p>
</section>
<section id="hypothesis-framing-the-research-question" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-framing-the-research-question">Hypothesis framing the research question</h2>
<p><em>Null Hypothesis (H₀):</em> The presence and extent of berry plantations in Jalisco municipalities are fully explained by agroclimatic conditions, number of people dedicated to agriculture, and proximity to federal highways. There is no additional spatial clustering effect beyond these variables.</p>
<p><em>Alternative Hypothesis (H₁):</em> Berry plantations exhibit spatial clustering that cannot be fully explained by agroclimatic conditions, demographics, or highway proximity — suggesting that proximity to other plantations (e.g., access to specialized services or cold storage) significantly influences their location.</p>
</section>
<section id="initial-coding-and-data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="initial-coding-and-data-preparation">Initial coding and data preparation</h2>
<p><em>0. Explore the shapefile for the 125 municipalities of Jalisco</em></p>
<p>The coordinates for the polygons corresponding to each of the 125 municipalities of Jalisco where retrieved from the government agency dedicated to demographic and geographic information, INEGI.</p>
<p>The shapefile has the 125 polyogons corresponding to each of the state’s municipalities</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LimiteMunicipal2012' from data source 
  `/home/jupyter-jf1677/gis-project/LimiteMunicipal2012/LimiteMunicipal2012.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 125 features and 6 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 427476 ymin: 2096902 xmax: 865450.6 ymax: 2515726
Projected CRS: WGS 84 / UTM zone 13N</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/JuanFinalProject-init-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="index_files/figure-html/JuanFinalProject-init-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<a class="quarto-notebook-link" id="nblink-1" href="index-preview.html">Source: Article Notebook</a></div>
<p><em>1. Calculate the average elevation for each municipality:</em></p>
<p>Install the elevatr package first</p>
<p>Computation of average elevation // this process takes time</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LimiteMunicipal2012' from data source 
  `/home/jupyter-jf1677/gis-project/LimiteMunicipal2012/LimiteMunicipal2012.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 125 features and 6 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 427476 ymin: 2096902 xmax: 865450.6 ymax: 2515726
Projected CRS: WGS 84 / UTM zone 13N</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                        municipio CVEGEO avg_elev_m
1                         TOLIMÁN  14099  1379.4055
2                           AMECA  14006  1417.4977
3                          CUQUÍO  14029  1836.5263
4                   CHIQUILISTLÁN  14032  1748.3932
5                          EJUTLA  14034  1243.8336
6                        ETZATLÁN  14036  1656.7115
7            AHUALULCO DE MERCADO  14003  1489.3812
8                       EL GRULLO  14037   997.3953
9                     GUADALAJARA  14039  1542.9333
10            IXTLAHUACÁN DEL RÍO  14045  1628.3559
11  IXTLAHUACÁN DE LOS MEMBRILLOS  14044  1625.1330
12                      JOCOTEPEC  14050  1809.8049
13                      MAGDALENA  14055  1503.3940
14        LA MANZANILLA DE LA PAZ  14057  2005.7822
15                      MAZAMITLA  14059  2007.6252
16                  JALOSTOTITLÁN  14046  1781.8458
17                     MEXTICACÁN  14060  1770.6769
18                       LA BARCA  14018  1561.6211
19                        OCOTLÁN  14063  1588.3158
20            SANTA MARÍA DEL ORO  14056  1018.7078
21                       QUITUPAN  14069  1863.5221
22        SAN DIEGO DE ALEJANDRÍA  14072  1948.9848
23                     SAN JULIÁN  14074  2032.0852
24                       AMATITÁN  14005  1310.7974
25                           TALA  14083  1517.9458
26             ZAPOTLÁN EL GRANDE  14023  1859.1488
27           TAMAZULA DE GORDIANO  14085  1524.0133
28           ATEMAJAC DE BRIZUELA  14010  2141.7643
29                     TECOLOTLÁN  14088  1613.0202
30        TECHALUTA DE MONTENEGRO  14089  1832.7636
31                         AYUTLA  14017  1681.6070
32                    TENAMAXTLÁN  14090  1538.1838
33         TEOCUITATLÁN DE CORONA  14092  1565.1251
34             SAN MARTÍN HIDALGO  14077  1426.6422
35                     TEUCHITLÁN  14095  1416.8931
36                    JUANACATLÁN  14051  1637.3709
37                         TONALÁ  14101  1547.9251
38                         TONAYA  14102  1098.2786
39                       EL LIMÓN  14054  1015.0370
40                    TUXCACUESCO  14106  1154.1904
41                         TUXPAN  14108  1166.5508
42                   VILLA CORONA  14114  1461.5384
43                 VILLA GUERRERO  14115  1622.9497
44             ZACOALCO DE TORRES  14119  1534.5614
45              ACATLÁN DE JUÁREZ  14002  1464.4200
46          ZAPOTITLÁN DE VADILLO  14122  1581.1665
47                    ZAPOTLANEJO  14124  1633.2711
48             SAN MIGUEL EL ALTO  14078  1996.7846
49        SAN IGNACIO CERRO GORDO  14125  2073.0176
50             ATOTONILCO EL ALTO  14013  1749.2610
51     SANTA MARÍA DE LOS ÁNGELES  14081  1996.6548
52                       HUEJÚCAR  14041  2102.6418
53                CABO CORRIENTES  14020   485.9602
54                      CIHUATLÁN  14022   222.7718
55                       COLOTLÁN  14025  1885.2064
56  CUAUTITLÁN DE GARCÍA BARRAGÁN  14027   973.7498
57                    CHIMALTITÁN  14031  1867.0779
58                      DEGOLLADO  14033  1787.9797
59            ENCARNACIÓN DE DÍAZ  14035  1928.3419
60                    GUACHINANGO  14038  1362.9060
61                HOSTOTIPAQUILLO  14040  1094.9773
62            HUEJUQUILLA EL ALTO  14042  1816.7955
63                      LA HUERTA  14043   274.5861
64                          JAMAY  14047  1554.0430
65                    JESÚS MARÍA  14048  2094.0072
66        JILOTLÁN DE LOS DOLORES  14049   803.8734
67                LAGOS DE MORENO  14053  2108.5503
68                      MEZQUITIC  14061  1699.7401
69             OJUELOS DE JALISCO  14064  2237.7287
70                        PIHUAMO  14065   916.1325
71                      PONCITLÁN  14066  1663.7686
72                PUERTO VALLARTA  14067   558.5513
73   SAN CRISTÓBAL DE LA BARRANCA  14071  1450.9049
74          SAN MARTÍN DE BOLAÑOS  14076  1530.5607
75        SAN SEBASTIÁN DEL OESTE  14080  1014.4107
76                     TECALITLÁN  14087  1477.7871
77                    TEOCALTICHE  14091  1808.4996
78                TIZAPÁN EL ALTO  14096  1771.4448
79                       TOMATLÁN  14100   299.4551
80                         TONILA  14103  1737.4695
81                  VILLA HIDALGO  14116  2047.3490
82    YAHUALICA DE GONZÁLEZ GALLO  14118  1910.5055
83                         ATOYAC  14014  1607.6494
84                       AMACUECA  14004  1795.9427
85        SAN JUANITO DE ESCOBEDO  14007  1439.3147
86                        ARANDAS  14008  2051.3884
87                      EL ARENAL  14009  1433.4950
88                         ATENGO  14011  1702.0692
89                     ATENGUILLO  14012  1804.5339
90              AUTLÁN DE NAVARRO  14015  1260.1133
91                        AYOTLÁN  14016  1707.0440
92                        BOLAÑOS  14019  1588.1345
93              CASIMIRO CASTILLO  14021   655.3625
94                         COCULA  14024  1468.6853
95     CONCEPCIÓN DE BUENOS AIRES  14026  2083.2466
96                        CUAUTLA  14028  1825.0711
97                         ACATIC  14001  1726.4443
98                        CHAPALA  14030  1714.1676
99                      JUCHITLÁN  14052  1280.3631
100                       MASCOTA  14058  1646.8033
101                       MIXTLÁN  14062  1616.5100
102            VILLA PURIFICACIÓN  14068   695.1448
103                      EL SALTO  14070  1555.9789
104         SAN JUAN DE LOS LAGOS  14073  1833.1132
105                    SAN MARCOS  14075  1446.2193
106                  GÓMEZ FARÍAS  14079  1911.3954
107                        SAYULA  14082  1713.0342
108              TALPA DE ALLENDE  14084  1225.8579
109                       TAPALPA  14086  2156.1718
110         TEPATITLÁN DE MORELOS  14093  1905.0121
111                       TEQUILA  14094  1448.9455
112          TLAJOMULCO DE ZÚÑIGA  14097  1653.8004
113                       ZAPOPAN  14120  1552.9981
114         SAN PEDRO TLAQUEPAQUE  14098  1583.8126
115                     TOTATICHE  14104  1839.9241
116                      TOTOTLÁN  14105  1633.3850
117                      TUXCUECA  14107  1832.1377
118          UNIÓN DE SAN ANTONIO  14109  1884.9209
119                 UNIÓN DE TULA  14110  1460.4676
120            VALLE DE GUADALUPE  14111  1863.7452
121               VALLE DE JUÁREZ  14112  2153.9226
122                   SAN GABRIEL  14113  1710.2040
123            CAÑADAS DE OBREGÓN  14117  1827.9254
124                    ZAPOTILTIC  14121  1349.5145
125              ZAPOTLÁN DEL REY  14123  1649.5954</code></pre>
</div>
</div>
<p><em>2. Calculate the average precipitation and temperatures for each municipality</em></p>
<p>Install the package for geodata:</p>
<p>Generate and save data:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LimiteMunicipal2012' from data source 
  `/home/jupyter-jf1677/gis-project/LimiteMunicipal2012/LimiteMunicipal2012.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 125 features and 6 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 427476 ymin: 2096902 xmax: 865450.6 ymax: 2515726
Projected CRS: WGS 84 / UTM zone 13N</code></pre>
</div>
</div>
<p><em>3. Export table with municipal averages (temperature and precipitation):</em></p>
<p><em>4. Calculate adjacency to determine municipalities neighboring a berries producer</em></p>
<p>For this I use a .dta file with information indicating which cvegeo (muncipality id) has berries</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LimiteMunicipal2012' from data source 
  `/home/jupyter-jf1677/gis-project/LimiteMunicipal2012/LimiteMunicipal2012.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 125 features and 6 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 427476 ymin: 2096902 xmax: 865450.6 ymax: 2515726
Projected CRS: WGS 84 / UTM zone 13N</code></pre>
</div>
</div>
</section>
<section id="variables-used-for-spatial-analysis" class="level2">
<h2 class="anchored" data-anchor-id="variables-used-for-spatial-analysis">Variables used for spatial analysis</h2>
<p>Consulting both official sources and self-generated data (using the codes above), this is the list of variables and data that will be used for spatial analysis:</p>
<p>Data source: <code>berries_jalisco_2024.dta</code><br>
Observations: 125 | Variables: 42 | Date: 12 Dec 2025</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>cvegeo</td>
<td>string</td>
<td>Municipality identifier (CVEGEO)</td>
</tr>
<tr class="even">
<td>municipality</td>
<td>string</td>
<td>Municipality name</td>
</tr>
<tr class="odd">
<td>berry_place</td>
<td>float</td>
<td>Has any berry production (indicator)</td>
</tr>
<tr class="even">
<td>neighbor_has_berries</td>
<td>integer</td>
<td>Neighboring municipality grows berries</td>
</tr>
<tr class="odd">
<td>blue</td>
<td>float</td>
<td>Produces blueberries (indicator)</td>
</tr>
<tr class="even">
<td>straw</td>
<td>float</td>
<td>Produces strawberries (indicator)</td>
</tr>
<tr class="odd">
<td>black</td>
<td>float</td>
<td>Produces blackberries (indicator)</td>
</tr>
<tr class="even">
<td>rasp</td>
<td>float</td>
<td>Produces raspberries (indicator)</td>
</tr>
<tr class="odd">
<td>berries_count</td>
<td>float</td>
<td>Number of different berries produced</td>
</tr>
<tr class="even">
<td>harvested_ha_total</td>
<td>float</td>
<td>Total harvested surface (ha)</td>
</tr>
<tr class="odd">
<td>surface_cat</td>
<td>integer</td>
<td>Surface category (by hectares dedicated to berries)</td>
</tr>
<tr class="even">
<td>prod_value_total</td>
<td>float</td>
<td>Total production value (MXN)</td>
</tr>
<tr class="odd">
<td>avg_elev_m</td>
<td>float</td>
<td>Average elevation (meters above sea level)</td>
</tr>
<tr class="even">
<td>annual_prec_mm</td>
<td>float</td>
<td>Annual precipitation (mm)</td>
</tr>
<tr class="odd">
<td>precipitation_good</td>
<td>float</td>
<td>Precipitation in optimal berry range (700–1200 mm)</td>
</tr>
<tr class="even">
<td>irrigation_ha_thousands</td>
<td>float</td>
<td>Thousands of irrigated hectares</td>
</tr>
<tr class="odd">
<td>labor_ag_thousands</td>
<td>float</td>
<td>Thousands of workers employed in agriculture</td>
</tr>
<tr class="even">
<td>with_federal_highway</td>
<td>byte</td>
<td>Municipality has a federal toll highway (indicator)</td>
</tr>
<tr class="odd">
<td>surface_perc_ag</td>
<td>float</td>
<td>Percent of municipal surface used for agriculture</td>
</tr>
</tbody>
</table>
</section>
<section id="simple-visualization-of-spatial-data" class="level2">
<h2 class="anchored" data-anchor-id="simple-visualization-of-spatial-data">Simple visualization of spatial data</h2>
<p><em>5. Generate idea maps</em></p>
<p>All maps will be stored in the project’s folder as .png files.</p>
<p>First run this cell to combine the geographic data (.shp) with the data about berries production.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LimiteMunicipal2012' from data source 
  `/home/jupyter-jf1677/gis-project/LimiteMunicipal2012/LimiteMunicipal2012.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 125 features and 6 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 427476 ymin: 2096902 xmax: 865450.6 ymax: 2515726
Projected CRS: WGS 84 / UTM zone 13N</code></pre>
</div>
</div>
<p><em>5.1. Municipalities that produce berries, indicating the number of hectares</em></p>
<p>This is essentially the Independent Variable (Production of berries), or variable of interest</p>
<p><a href="images/jalisco1_berry_map.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="images/jalisco1_berry_map.png" class="img-fluid"></a></p>
<p><em>5.2 Municipalities classified by average Elevation</em></p>
<p>&amp;</p>
<p><em>5.3 Municipalities classified by annual Precipitation</em></p>
<p><a href="images/jalisco2_elevation_map.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="images/jalisco2_elevation_map.png" class="img-fluid"></a></p>
<p><a href="images/jalisco3_precipitation_map.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="images/jalisco3_precipitation_map.png" class="img-fluid"></a></p>
<p><em>5.4 Municipalities with Federal Highways</em></p>
<p><a href="images/jalisco4_highway_map.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="images/jalisco4_highway_map.png" class="img-fluid"></a></p>
<p><em>5.5 Number of people employed in agriculture</em></p>
<p><a href="images/jalisco5_agricultural_labor_map.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="images/jalisco5_agricultural_labor_map.png" class="img-fluid"></a></p>
<p><em>5.6 Hectares dedicated to agriculture with irrigation system per municipality</em></p>
<p><a href="images/jalisco6_irrigation_map.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="images/jalisco6_irrigation_map.png" class="img-fluid"></a></p>
</section>
<section id="non-spatial-correlation" class="level2">
<h2 class="anchored" data-anchor-id="non-spatial-correlation">Non-Spatial Correlation</h2>
<p><em>6. The standard OLS regression with explanatory variables.</em></p>
<p>Using simple OLS regression with information avaible, we will assess the predictors for observing berries plantations in a municipality in Jalisco.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = berry_place ~ avg_elev_m + irrigation_ha_thousands + 
    precipitation_good + labor_ag_thousands + with_federal_highway + 
    surface_perc_ag, data = jalisco_mun)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.7769 -0.2841 -0.1051  0.3764  1.0500 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)             -2.879e-01  1.865e-01  -1.544  0.12526   
avg_elev_m               2.256e-04  9.835e-05   2.294  0.02356 * 
irrigation_ha_thousands  2.423e-02  1.719e-02   1.409  0.16140   
precipitation_good       3.082e-01  9.337e-02   3.301  0.00127 **
labor_ag_thousands       1.715e-02  7.724e-03   2.221  0.02829 * 
with_federal_highway     9.456e-02  8.594e-02   1.100  0.27342   
surface_perc_ag         -3.872e-01  2.014e-01  -1.922  0.05700 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4033 on 118 degrees of freedom
Multiple R-squared:  0.2745,    Adjusted R-squared:  0.2376 
F-statistic: 7.439 on 6 and 118 DF,  p-value: 9.052e-07</code></pre>
</div>
</div>
<p>RESULTS:</p>
<p>Residuals: Min 1Q Median 3Q Max -0.7769 -0.2841 -0.1051 0.3764 1.0500</p>
<p>Coefficients: Estimate Std. Error t value Pr(&gt;|t|)<br>
(Intercept) -2.879e-01 1.865e-01 -1.544 0.12526<br>
avg_elev_m 2.256e-04 9.835e-05 2.294 0.02356 * irrigation_ha_thousands 2.423e-02 1.719e-02 1.409 0.16140<br>
precipitation_good 3.082e-01 9.337e-02 3.301 0.00127 <strong>labor_ag_thousands 1.715e-02 7.724e-03 2.221 0.02829 * with_federal_highway 9.456e-02 8.594e-02 1.100 0.27342<br>
surface_perc_ag -3.872e-01 2.014e-01 -1.922 0.05700 . — Signif. codes: 0 ’</strong>*’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</p>
<p>Residual standard error: 0.4033 on 118 degrees of freedom Multiple R-squared: 0.2745, Adjusted R-squared: 0.2376 F-statistic: 7.439 on 6 and 118 DF, p-value: 9.052e-07</p>
<p>INTERPRETATION:</p>
<p>So far, from the non-spatial model, we know that the only significant variables —all of them positively correlated— that help to predict berries plantation are: - Precipitation being in optimal conditions for berries has p-value of 0.001 - Average elevation of the municipality has a p-value of 0.024 - Number of workers dedicated to agriculture has a p-value of 0.028</p>
<p>Surface dedicated to agriculture is negatively correlated. This means that larger municipalities with more extensive areas for agriculture is not in close relationship with this particular crop.</p>
</section>
<section id="spatial-correlation-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="spatial-correlation-morans-i">Spatial Correlation: Moran’s I</h2>
<p><em>7. Compute Moran’s I on the residuals</em></p>
<p>Before moving to spatial lag regression, we check whether residuals are spatially autocorrelated.</p>
<p>Steps: - Build a spatial weights matrix (based on municipality adjacency or distance). - Compute Moran’s I on the residuals of your OLS model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  residuals(ols_model)  
weights: lw    

Moran I statistic standard deviate = 3.7265, p-value = 9.708e-05
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.215528846      -0.008064516       0.003600136 </code></pre>
</div>
</div>
<p>RESULTS:</p>
<pre><code>Moran I test under randomisation</code></pre>
<p>data: residuals(ols_model)<br>
weights: lw</p>
<p>Moran I statistic standard deviate = 3.7265, p-value = 9.708e-05 alternative hypothesis: greater sample estimates: Moran I statistic Expectation Variance 0.215528846 -0.008064516 0.003600136</p>
<p>INTERPRETATION:</p>
<ul>
<li>Moran’s I statistic = 0.216 → Positive and moderate spatial autocorrelation.</li>
<li>Expectation = -0.008 → What Moran’s I would be under pure randomness (close to zero).</li>
<li>Standard deviate = 3.73, p-value ≈ 0.000097 → Highly significant.</li>
</ul>
<p>This means your OLS residuals are spatially clustered: municipalities with similar residuals are near each other. In other words, the non‑spatial regression is missing spatial dynamics.</p>
</section>
<section id="spatial-lag-regresion" class="level2">
<h2 class="anchored" data-anchor-id="spatial-lag-regresion">Spatial Lag Regresion</h2>
<p><em>8. Add a neighbors’ berry presence as a predictor</em></p>
<p>Whether the neighboring municipality produces berries is a spatially lagged dependent variable.</p>
<p>code for regression here:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:lagsarlm(formula = berry_place ~ avg_elev_m + irrigation_ha_thousands + 
    precipitation_good + labor_ag_thousands + with_federal_highway + 
    surface_perc_ag, data = jalisco_mun, listw = lw)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.688500 -0.241734 -0.045194  0.246270  0.825377 

Type: lag 
Coefficients: (asymptotic standard errors) 
                           Estimate  Std. Error z value Pr(&gt;|z|)
(Intercept)             -2.7028e-01  1.6825e-01 -1.6064  0.10818
avg_elev_m               2.0599e-04  8.9389e-05  2.3044  0.02120
irrigation_ha_thousands  2.1573e-02  1.5513e-02  1.3907  0.16432
precipitation_good       1.7671e-01  8.5875e-02  2.0577  0.03962
labor_ag_thousands       1.4783e-02  7.0064e-03  2.1099  0.03487
with_federal_highway     5.2283e-02  7.8870e-02  0.6629  0.50739
surface_perc_ag         -3.4450e-01  1.8246e-01 -1.8881  0.05901

Rho: 0.38954, LR test value: 13.979, p-value: 0.00018485
Asymptotic standard error: 0.098396
    z-value: 3.9589, p-value: 7.528e-05
Wald statistic: 15.673, p-value: 7.528e-05

Log likelihood: -53.25478 for lag model
ML residual variance (sigma squared): 0.1324, (sigma: 0.36387)
Number of observations: 125 
Number of parameters estimated: 9 
AIC: 124.51, (AIC for lm: 136.49)
LM test for residual autocorrelation
test value: 0.48735, p-value: 0.48511</code></pre>
</div>
</div>
<p>RESULTS SPATIAL LAG MODEL:</p>
<p>Residuals: Min 1Q Median 3Q Max -0.688500 -0.241734 -0.045194 0.246270 0.825377</p>
<p>Type: lag Coefficients: (asymptotic standard errors) Estimate Std. Error z value Pr(&gt;|z|) (Intercept) -2.7028e-01 1.6825e-01 -1.6064 0.10818 avg_elev_m 2.0599e-04 8.9389e-05 2.3044 0.02120 irrigation_ha_thousands 2.1573e-02 1.5513e-02 1.3907 0.16432 precipitation_good 1.7671e-01 8.5875e-02 2.0577 0.03962 labor_ag_thousands 1.4783e-02 7.0064e-03 2.1099 0.03487 with_federal_highway 5.2283e-02 7.8870e-02 0.6629 0.50739 surface_perc_ag -3.4450e-01 1.8246e-01 -1.8881 0.05901</p>
<p>Rho: 0.38954, LR test value: 13.979, p-value: 0.00018485 Asymptotic standard error: 0.098396 z-value: 3.9589, p-value: 7.528e-05 Wald statistic: 15.673, p-value: 7.528e-05</p>
<p>Log likelihood: -53.25478 for lag model ML residual variance (sigma squared): 0.1324, (sigma: 0.36387) Number of observations: 125 Number of parameters estimated: 9 AIC: 124.51, (AIC for lm: 136.49) LM test for residual autocorrelation test value: 0.48735, p-value: 0.48511</p>
<p>INTERPRETATION:</p>
<ul>
<li><p>Rho (ρ) = 0.39, p &lt; 0.001 → Strong and statistically significant spatial dependence. Berry cultivation in one municipality is positively associated with cultivation in neighboring municipalities. This confirms the clustering effect you suspected.</p></li>
<li><p>Model fit (AIC = 124.5 vs OLS AIC = 136.5) → The spatial lag model fits better than the OLS baseline. Lower AIC means the SAR model explains the data more efficiently.</p></li>
<li><p>Residual autocorrelation test (LM test p = 0.485) → No significant spatial autocorrelation remains in the residuals. This means the lag model successfully absorbed the spatial clustering that OLS left behind.</p></li>
<li><p>Significant predictors: Altitude (avg_elev_m, p = 0.021) → Higher elevation increases likelihood of berry cultivation. Precipitation_good (p = 0.040) → Favorable precipitation conditions matter. Labor_ag_thousands (p = 0.035) → More agricultural workers increase berry cultivation. Surface_perc_ag (p = 0.059, marginal) → Higher share of land in agriculture is negatively associated (possibly competition with other crops).</p></li>
<li><p>Non‑significant predictors: Irrigation hectares (p = 0.16) Federal highway presence (p = 0.51)</p></li>
</ul>
</section>
<section id="conclusion-of-the-spatial-analysis" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-of-the-spatial-analysis">Conclusion of the spatial analysis</h2>
<p>The Spatial Lag Model shows that neighboring municipalities’ berry cultivation has a strong spillover effect (ρ ≈ 0.39). This validates the hypothesis about clustering: berries are not only driven by agroclimatic and labor conditions, but also by spatial dynamics such as proximity to existing plantations, services, or cold storage.</p>
<p><em>Policy interpretation</em></p>
<ul>
<li>Spatial spillovers suggest that supporting clusters (e.g., infrastructure, cold storage hubs) could amplify berry expansion.</li>
<li>Agroclimatic suitability and labor availability remain key, but clustering magnifies their effect</li>
</ul>
<p><em>Policy implications</em></p>
<p>The spatial lag analysis confirms that berry cultivation in Jalisco is not only shaped by agroclimatic suitability and labor availability, but also by strong spillover effects from neighboring municipalities. This clustering dynamic suggests that subsidies for agricultural technologies will have greater impact if they are targeted toward municipalities already embedded in or adjacent to existing berry production zones.</p>
<p>By concentrating support in these clusters—such as precision irrigation, cold storage facilities, or improved transport logistics—the Department of Agriculture can leverage spatial spillovers to accelerate adoption and productivity gains. At the same time, prioritizing areas with favorable altitude and precipitation conditions ensures that subsidies align with natural suitability, while recognizing that labor-intensive production requires complementary investments in workforce training.</p>
<p>In practice, this means that subsidy programs should not be distributed uniformly across the state, but strategically directed to municipalities where agroclimatic advantages and spatial clustering combine to maximize the likelihood of sustained expansion in berry cultivation.</p>
</section>
<section id="sources-of-information-and-data" class="level2">
<h2 class="anchored" data-anchor-id="sources-of-information-and-data">Sources of information and data</h2>
<p>Servicio Nacional de Sanidad, Inocuidad y Calidad Agroalimentaria (SENASICA). (2025, August 6). Berries, second product of the field with the highest export value: Agriculture. Gobierno de México. https://www.gob.mx/senasica/documentos/berries-second-product-of-the-field-with-the-highest-export-value-agriculture</p>
<p><em>Hectares of berries harvested</em></p>
<p>Source: https://nube.agricultura.gob.mx/cierre_agricola/ Anuario Estadístico de la Producción Agrícola, 2024. Secretaría de Agricultura 2024: Arandano, Frambuesa, Zarzamora, Fresa – for any market, any production modality</p>
<p><em>Percentage of surface dedicated to agriculture</em></p>
<p>Source: https://www.inegi.org.mx/contenidos/programas/ca/2022/datosabiertos/ca_2022_superficie_csv.zip Censo Agropecuario 2022. INEGI</p>
<p><em>Surface with irrigation in hectares, and labor dedicated to agriculture</em></p>
<p>Source: https://www.inegi.org.mx/contenidos/programas/ca/2022/datosabiertos/ca_2022_upagro_csv.zip Censo Agropecuario 2022. INEGI</p>
<p><em>Highways in Jalisco</em></p>
<p>Red Nacional de Caminos https://en.www.inegi.org.mx/app/biblioteca/ficha.html?upc=794551132166</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>